name: Presentation
on: 
  push:
    tags:
      - pdf_**
jobs:
  presentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run LaTeX
        uses: xu-cheng/texlive-action@v3
        with:
          scheme: full
          run: |
            make -C tex pf2025.pdf
            mv tex/pf2025.pdf .
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Presentation
          files: pf2025.pdf
